apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-{{USER}}-{{ID}}
  namespace: backend
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
  - "--context=git://github.com/nickthelegend/backend-kubernetes.git#refs/heads/main"
  - "--dockerfile=/workspace/Dockerfile"
  - "--destination=registry.digitalocean.com/orca-registry/backend:v1.0"
  - "--verbosity=info"

          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
              readOnly: true
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
