apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-nivesh-001
  namespace: backend
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            # Replace with your repo
            - "--context=git://github.com/nickthelegend/backend-kubernetes.git#refs/heads/main"

            # If your Dockerfile is in root of repo
            - "--dockerfile=Dockerfile"

            # Change this to your registry path
            - "--destination=registry.digitalocean.com/orcanet/backend-kubernetes:v1.0"

            # Optional (more detailed logs)
            - "--verbosity=debug"

          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
              readOnly: true
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
