name: Build & Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build . -t ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Image details
        run: |
          docker image inspect ghcr.io/${{ github.repository_owner }}/backend:latest
